import featureData from "./features-2025.json";

const RoadLabelFont = "Museo Sans 700";
const RoadCasingColor = "#F4CE99";
const RoadsMinorColor = "#fdf3d7";
const RoadsMinorCasingWidth = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  15,
  1,
  16,
  2,
];
const RoadsMinorWidth = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  13,
  5,
  15,
  7,
  17.5,
  12,
  20,
  30,
];
const RoadsServiceWidth = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  15,
  4,
  17.5,
  10,
  20,
  30,
];
const RoadsMajorColor = "#fffce1";
const RoadsMajorWidth = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  13,
  8,
  15,
  14,
  18,
  14,
];
const RoadMajorLabelSize = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  15,
  12,
  18,
  11,
];
const RoadsMajorCasingWidth = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  15,
  1,
  18,
  2,
];
const BuildingShadowColor = "#F4CE99";
const RoadsTertiaryColor = "#fdf3d7";
const RoadsTertiaryWidth = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  13,
  8,
  15,
  15,
  18,
  12,
];
const RoadsHighwayColor = "#d9b692";
const RoadsHighwayWidth = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  13,
  14,
  15,
  22,
  18,
  32,
];
const LandColor = "#f9eacc";
const BuildingColor = [
  "interpolate",
  ["linear", 1],
  ["zoom"],
  15,
  "#E1B377",
  18,
  "#F9D5A3",
];
const PoiTextSize = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  15,
  15,
  18,
  18,
  20,
  22,
];

const PoiIconSize = ["interpolate", ["linear", 1], ["zoom"], 17, 0.75, 20, 1.0];
const AreaColor = "#E97424";

const RoadsMinorLabelSize = 10;
const RoadsTertiaryLabelSize = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  15,
  11,
  18,
  10,
];
const RoadsHighwayLabelSize = [
  "interpolate",
  ["exponential", 1.6],
  ["zoom"],
  15,
  18,
  18,
  13,
];
export default {
  version: 8,
  glyphs: "./fonts/{fontstack}/{range}.pbf",
  sprite: "./sprites/sprite",
  sources: {
    protomaps: {
      type: "vector",
      url: "pmtiles://./tiles/halloween-parade.pmtiles",
    },
    features: {
      type: "geojson",
      data: featureData,
    },
  },
  layers: [
    /**
     * Background
     */
    {
      id: "background",
      type: "background",
      paint: { "background-color": LandColor },
    },
    {
      id: "earth",
      type: "fill",
      filter: ["==", ["geometry-type"], "Polygon"],
      source: "protomaps",
      "source-layer": "earth",
      paint: { "fill-color": LandColor },
    },
    /**
     * Parks
     */
    {
      id: "landuse_park",
      type: "fill",
      source: "protomaps",
      "source-layer": "landuse",
      filter: [
        "in",
        "kind",
        "national_park",
        "park",
        "cemetery",
        "protected_area",
        "nature_reserve",
        "forest",
        "golf_course",
      ],

      paint: {
        "fill-opacity": 0.25,
        "fill-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          "#98CC68",
          12,
          "#A0D572",
        ],
      },
    },
    {
      id: "landuse_urban_green",
      type: "fill",
      source: "protomaps",
      "source-layer": "landuse",
      filter: ["in", "kind", "allotments", "village_green", "playground"],
      paint: { "fill-color": "#9cd3b4", "fill-opacity": 0.25 },
    },
    /**
     * Schools
     */
    {
      id: "landuse_school",
      type: "fill",
      source: "protomaps",
      "source-layer": "landuse",
      filter: ["in", "kind", "school", "university", "college"],
      paint: { "fill-color": "#e4ded7", "fill-opacity": 0.5 },
    },

    /**
     * Area Outlines
     */
    {
      id: "festival-area",
      type: "fill",
      source: "features",
      filter: [
        "any",
        ["==", "kind", "festival-outline"],
        ["==", "kind", "downtown-area"],
      ],
      layout: {},
      paint: {
        "fill-color": AreaColor,
        "fill-color": [
          "interpolate",
          ["exponential", 2],
          ["zoom"],
          15,
          AreaColor,
          17,
          LandColor,
        ],
        "fill-opacity": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          15,
          0.85,
          18,
          0,
        ],
      },
    },
    // {
    //   id: "festival-area-outline",
    //   type: "line",
    //   source: "features",
    //   filter: ["==", "kind", "festival-outline"],
    //   layout: {},
    //   paint: {
    //     "line-color": [
    //       "interpolate",
    //       ["exponential", 2],
    //       ["zoom"],
    //       15,
    //       areaColor,
    //       17,
    //       "#FED777",
    //     ],
    //     "line-opacity": [
    //       "interpolate",
    //       ["linear", 1],
    //       ["zoom"],
    //       15,
    //       1,
    //       18,
    //       0.5,
    //     ],
    //     "line-width": ["interpolate", ["linear", 1], ["zoom"], 15, 4, 18, 2],
    //   },
    // },

    /**
     * Buildings
     */
    {
      id: "buildings_shadow",
      type: "fill",
      source: "protomaps",
      "source-layer": "buildings",
      paint: {
        "fill-color": BuildingShadowColor,
        "fill-translate": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          16,
          ["literal", [1, 0]],
          18,
          ["literal", [3, 4]],
        ],
        "fill-opacity": [
          "interpolate",
          ["exponential", 2],
          ["zoom"],
          15,
          0.25,
          17,
          1,
        ],
      },
    },
    {
      id: "buildings",
      type: "fill",
      source: "protomaps",
      "source-layer": "buildings",
      paint: {
        "fill-color": BuildingColor,
        "fill-color": [
          "interpolate",
          ["exponential", 2],
          ["zoom"],
          15,
          "#F5E2BF",
          17,
          "#F9D5A3",
        ],
      },
    },
    {
      id: "buildings_outline",
      type: "line",
      source: "protomaps",
      "source-layer": "buildings",
      paint: {
        "line-color": "#F4CE99",
        "line-width": [
          "interpolate",
          ["exponential", 2],
          ["zoom"],
          15,
          0,
          16.5,
          1,
        ],
      },
    },

    /**
     * Road Casings
     */
    {
      id: "roads_minor_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "minor_road"],
        ["!=", "kind_detail", "service"],
      ],
      layout: { "line-cap": "round" },
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsMinorWidth,
        "line-width": RoadsMinorCasingWidth,
      },
    },
    {
      id: "roads_link_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 13,
      filter: ["has", "is_link"],
      layout: { "line-cap": "round" },
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsServiceWidth,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          1.5,
        ],
      },
    },
    {
      id: "roads_service_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 13,
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "minor_road"],
        ["==", "kind_detail", "service"],
      ],
      layout: { "line-cap": "round" },
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsServiceWidth,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          0.8,
        ],
      },
    },
    {
      id: "roads_tertiary_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "major_road"],
        ["==", "kind_detail", "tertiary"],
      ],
      layout: { "line-cap": "round" },
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsTertiaryWidth,
        "line-width": RoadsMajorCasingWidth,
      },
    },
    {
      id: "roads_major_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",

      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "major_road"],
        ["!=", "kind_detail", "primary_link"],
        [
          "any",
          ["==", "kind_detail", "primary"],
          ["==", "kind_detail", "secondary"],
        ],
      ],
      layout: { "line-cap": "round" },
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsMajorWidth,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          1,
          18,
          3,
        ],
      },
    },
    {
      id: "roads_highway_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 12,
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "highway"],
        ["!has", "is_link"],
      ],
      layout: { "line-cap": "round" },
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsHighwayWidth,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          4,
          20,
          10,
        ],
      },
    },
    /**
     * Roads
     */
    {
      id: "roads_minor",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "minor_road"],
        ["!=", "kind_detail", "service"],
      ],
      layout: { "line-cap": "round" },

      paint: {
        "line-color": RoadsMinorColor,
        "line-width": RoadsMinorWidth,
      },
    },
    {
      id: "roads_minor_service",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "minor_road"],
        ["==", "kind_detail", "service"],
      ],
      layout: { "line-cap": "round" },

      paint: {
        "line-color": RoadsMinorColor,
        "line-width": RoadsServiceWidth,
      },
    },
    {
      id: "roads_link",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: ["has", "is_link"],
      paint: {
        "line-color": RoadsMinorColor,
        "line-width": RoadsServiceWidth,
      },
    },
    {
      id: "roads_tertiary",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "major_road"],
        ["==", "kind_detail", "tertiary"],
      ],
      paint: {
        "line-color": RoadsTertiaryColor,
        "line-width": RoadsTertiaryWidth,
      },
    },
    {
      id: "roads_highway",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "highway"],
        ["!has", "is_link"],
      ],
      paint: {
        "line-color": RoadsHighwayColor,
        "line-width": RoadsHighwayWidth,
      },
    },
    {
      id: "roads_major",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        [
          "any",
          ["==", "kind_detail", "primary"],
          ["==", "kind_detail", "secondary"],
        ],
      ],
      paint: {
        "line-color": RoadsMajorColor,
        "line-width": RoadsMajorWidth,
      },
    },
    {
      id: "roads_bridges_minor_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",

      filter: ["all", ["has", "is_bridge"], ["==", "kind", "minor_road"]],
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsMinorWidth,
        "line-width": RoadsMinorCasingWidth,
      },
    },
    {
      id: "roads_bridges_major_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 12,
      filter: [
        "all",
        ["has", "is_bridge"],
        ["==", "kind", "major_road"],
        [
          "any",
          ["==", "kind_detail", "primary"],
          ["==", "kind_detail", "secondary"],
        ],
      ],
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": RoadsMajorWidth,
        "line-width": RoadsMajorCasingWidth,
      },
    },
    {
      id: "roads_bridges_minor",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",

      filter: ["all", ["has", "is_bridge"], ["==", "kind", "minor_road"]],
      paint: {
        "line-color": RoadsMinorColor,
        "line-width": RoadsMinorWidth,
      },
    },
    {
      id: "roads_bridges_major",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 12,
      filter: [
        "all",
        ["has", "is_bridge"],
        ["==", "kind", "major_road"],
        [
          "any",
          ["==", "kind_detail", "primary"],
          ["==", "kind_detail", "secondary"],
        ],
      ],
      paint: {
        "line-color": RoadsMajorColor,
        "line-width": RoadsMajorWidth,
      },
    },
    {
      id: "roads_bridges_tertiary",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["has", "is_bridge"],
        ["==", "kind", "major_road"],
        ["any", ["==", "kind_detail", "tertiary"]],
      ],
      layout: { "line-cap": "round" },
      paint: {
        "line-color": RoadsTertiaryColor,
        "line-width": RoadsTertiaryWidth,
      },
    },
    {
      id: "roads_bridges_highway_casing",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 12,
      filter: [
        "all",
        ["has", "is_bridge"],
        ["==", "kind", "highway"],
        ["!has", "is_link"],
      ],
      paint: {
        "line-color": RoadCasingColor,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          3.5,
          0.5,
          18,
          15,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          1,
          20,
          15,
        ],
      },
    },
    {
      id: "roads_bridges_highway",
      type: "line",
      source: "protomaps",
      "source-layer": "roads",
      filter: [
        "all",
        ["has", "is_bridge"],
        ["==", "kind", "highway"],
        ["!has", "is_link"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          6,
          1.1,
          12,
          1.6,
          15,
          5,
          18,
          15,
        ],
      },
    },
    /**
     * Walking Routes
     */
    {
      id: "walking_routes",
      type: "line",
      source: "features",
      filter: ["==", "kind", "walking-route"],
      layout: {
        "line-join": "round",
        "line-cap": "round",
      },
      paint: {
        "line-color": "#FF7602",
        "line-dasharray": [1, 3],
        "line-width": 2,
      },
    },
    /**
     * Parade Route
     */
    {
      id: "parade_route",
      type: "line",
      source: "features",
      filter: ["==", "kind", "parade-route"],
      layout: {
        "line-join": "round",
        "line-cap": "round",
      },
      paint: {
        "line-color": "#FF7602",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          6,
          18,
          4,
        ],
        "line-opacity": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          1,
          18,
          1,
        ],
      },
    },
    {
      id: "parade_casing",
      type: "line",
      source: "features",
      filter: ["==", "kind", "parade-route"],
      layout: {
        "line-join": "round",
        "line-cap": "round",
      },
      paint: {
        "line-color": "#FFFCE1",
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          8,
          18,
          6,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          2,
          17,
          1,
          18,
          0,
        ],
        "line-opacity": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          1,
          18,
          0,
        ],
      },
    },
    {
      id: "parade_start",
      type: "circle",
      source: "features",
      filter: ["==", "kind", "parade-start"],
      paint: {
        "circle-color": "#FF7602",
        "circle-radius": 10,
      },
    },
    {
      id: "parade_end",
      type: "circle",
      source: "features",
      filter: ["==", "kind", "parade-end"],
      paint: {
        "circle-color": "#FF7602",
        "circle-radius": 10,
      },
    },
    /**
     * Road Labels
     */
    {
      id: "roads_labels_minor",
      type: "symbol",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 16,
      filter: ["in", "kind", "minor_road", "other", "path"],
      layout: {
        "symbol-placement": "line",
        "text-font": [RoadLabelFont],
        "text-field": [
          "case",
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["!", ["any", ["has", "name2"], ["has", "pgf:name2"]]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["has", "script"],
            [
              "case",
              [
                "any",
                ["is-supported-script", ["get", "name"]],
                ["has", "pgf:name"],
              ],
              [
                "format",
                ["coalesce", ["get", "name:undefined"], ["get", "name:en"]],
                {},
                "\n",
                {},
                [
                  "case",
                  [
                    "all",
                    ["!", ["has", "name:undefined"]],
                    ["has", "name:en"],
                    ["!", ["has", "script"]],
                  ],
                  "",
                  ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                ],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["get", "name:en"],
            ],
            [
              "format",
              [
                "coalesce",
                ["get", "name:undefined"],
                ["get", "pgf:name"],
                ["get", "name"],
              ],
              {},
            ],
          ],
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["any", ["has", "name2"], ["has", "pgf:name2"]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["has", "script2"],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"], ["has", "script3"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script3"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["!", ["has", "script"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["!", ["has", "script2"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name3"],
                  ["get", "name3"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
        ],
        "text-size": RoadsMinorLabelSize,
        "symbol-spacing": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          15,
          225,
          16,
          250,
          20,
          500,
        ],
      },
      paint: {
        "text-color": "#B17048",
        "text-halo-color": RoadsMinorColor,
        "text-halo-width": 2,
      },
    },
    {
      id: "roads_tertiary_labels",
      type: "symbol",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 11,
      filter: [
        "all",
        ["in", "kind", "major_road"],
        ["in", "kind_detail", "tertiary"],
      ],
      layout: {
        "symbol-placement": "line",
        "text-font": [RoadLabelFont],
        "text-field": [
          "case",
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["!", ["any", ["has", "name2"], ["has", "pgf:name2"]]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["has", "script"],
            [
              "case",
              [
                "any",
                ["is-supported-script", ["get", "name"]],
                ["has", "pgf:name"],
              ],
              [
                "format",
                ["coalesce", ["get", "name:undefined"], ["get", "name:en"]],
                {},
                "\n",
                {},
                [
                  "case",
                  [
                    "all",
                    ["!", ["has", "name:undefined"]],
                    ["has", "name:en"],
                    ["!", ["has", "script"]],
                  ],
                  "",
                  ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                ],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["get", "name:en"],
            ],
            [
              "format",
              [
                "coalesce",
                ["get", "name:undefined"],
                ["get", "pgf:name"],
                ["get", "name"],
              ],
              {},
            ],
          ],
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["any", ["has", "name2"], ["has", "pgf:name2"]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["has", "script2"],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"], ["has", "script3"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script3"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["!", ["has", "script"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["!", ["has", "script2"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name3"],
                  ["get", "name3"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
        ],
        "text-size": RoadsTertiaryLabelSize,
      },
      paint: {
        "text-color": "#B17048",
        "text-halo-color": RoadsTertiaryColor,
        "text-halo-width": 2,
      },
    },
    {
      id: "roads_major_labels",
      type: "symbol",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 11,
      filter: [
        "all",
        ["in", "kind", "major_road"],
        ["in", "kind_detail", "primary", "secondary"],
      ],
      layout: {
        "symbol-spacing": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          15,
          225,
          16,
          250,
          20,
          150,
        ],
        "symbol-placement": "line",
        "text-font": [RoadLabelFont],
        "text-field": [
          "case",
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["!", ["any", ["has", "name2"], ["has", "pgf:name2"]]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["has", "script"],
            [
              "case",
              [
                "any",
                ["is-supported-script", ["get", "name"]],
                ["has", "pgf:name"],
              ],
              [
                "format",
                ["coalesce", ["get", "name:undefined"], ["get", "name:en"]],
                {},
                "\n",
                {},
                [
                  "case",
                  [
                    "all",
                    ["!", ["has", "name:undefined"]],
                    ["has", "name:en"],
                    ["!", ["has", "script"]],
                  ],
                  "",
                  ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                ],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["get", "name:en"],
            ],
            [
              "format",
              [
                "coalesce",
                ["get", "name:undefined"],
                ["get", "pgf:name"],
                ["get", "name"],
              ],
              {},
            ],
          ],
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["any", ["has", "name2"], ["has", "pgf:name2"]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["has", "script2"],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"], ["has", "script3"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script3"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["!", ["has", "script"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["!", ["has", "script2"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name3"],
                  ["get", "name3"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
        ],
        "text-size": RoadMajorLabelSize,
      },
      paint: {
        "text-color": "#B17048",
        "text-halo-color": RoadsMajorColor,
        "text-halo-width": 3,
      },
    },
    {
      id: "roads_highway_labels",
      type: "symbol",
      source: "protomaps",
      "source-layer": "roads",
      minzoom: 11,
      filter: ["all", ["in", "kind", "highway"]],
      layout: {
        "symbol-placement": "line",
        "text-ignore-placement": true,
        "text-font": [RoadLabelFont],
        "text-field": [
          "case",
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["!", ["any", ["has", "name2"], ["has", "pgf:name2"]]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["has", "script"],
            [
              "case",
              [
                "any",
                ["is-supported-script", ["get", "name"]],
                ["has", "pgf:name"],
              ],
              [
                "format",
                ["coalesce", ["get", "name:undefined"], ["get", "name:en"]],
                {},
                "\n",
                {},
                [
                  "case",
                  [
                    "all",
                    ["!", ["has", "name:undefined"]],
                    ["has", "name:en"],
                    ["!", ["has", "script"]],
                  ],
                  "",
                  ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                ],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["get", "name:en"],
            ],
            [
              "format",
              [
                "coalesce",
                ["get", "name:undefined"],
                ["get", "pgf:name"],
                ["get", "name"],
              ],
              {},
            ],
          ],
          [
            "all",
            ["any", ["has", "name"], ["has", "pgf:name"]],
            ["any", ["has", "name2"], ["has", "pgf:name2"]],
            ["!", ["any", ["has", "name3"], ["has", "pgf:name3"]]],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["has", "script2"],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
          [
            "case",
            ["all", ["has", "script"], ["has", "script2"], ["has", "script3"]],
            [
              "format",
              ["get", "name:undefined"],
              {},
              "\n",
              {},
              ["coalesce", ["get", "pgf:name"], ["get", "name"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script2"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
              "\n",
              {},
              ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
              {
                "text-font": [
                  "case",
                  ["==", ["get", "script3"], "Devanagari"],
                  ["literal", [RoadLabelFont]],
                  ["literal", [RoadLabelFont]],
                ],
              },
            ],
            [
              "case",
              ["!", ["has", "script"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name"],
                  ["get", "name"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              ["!", ["has", "script2"]],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name2"],
                  ["get", "name2"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name3"], ["get", "name3"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script3"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
              [
                "format",
                [
                  "coalesce",
                  ["get", "name:undefined"],
                  ["get", "pgf:name3"],
                  ["get", "name3"],
                ],
                {},
                "\n",
                {},
                ["coalesce", ["get", "pgf:name"], ["get", "name"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
                "\n",
                {},
                ["coalesce", ["get", "pgf:name2"], ["get", "name2"]],
                {
                  "text-font": [
                    "case",
                    ["==", ["get", "script2"], "Devanagari"],
                    ["literal", [RoadLabelFont]],
                    ["literal", [RoadLabelFont]],
                  ],
                },
              ],
            ],
          ],
        ],
        "text-size": RoadsHighwayLabelSize,
        "text-offset": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          15,
          ["literal", [-0.5, -0.5]],
          16.5,
          ["literal", [0, 0]],
        ],
      },
      paint: {
        "text-color": "#B17048",
        "text-opacity": 0.5,
      },
    },
    {
      id: "walking_route_label",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "walking-route"],
      layout: {
        "symbol-placement": "line",
        "text-allow-overlap": false,
        "symbol-spacing": 175,
        "text-field": "{label}",
        "text-font": ["HeroSandwichPro Bold"],
        "text-size": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          18,
          18,
          14,
        ],
      },
      paint: {
        "text-color": "#FF7602",
        "text-halo-color": RoadsMajorColor,
        "text-halo-width": 2,
      },
    },
    {
      id: "parade_route_label",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "parade-route"],
      layout: {
        "symbol-placement": "line",
        "text-allow-overlap": true,
        "symbol-spacing": [
          "interpolate",
          ["linear", 1],
          ["zoom"],
          15,
          150,
          17,
          300,
          20,
          450,
        ],
        "text-field": "{label}",
        "text-font": ["Chickweed Titling Regular"],
        "text-size": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          15,
          20,
          18,
          16,
        ],
      },
      paint: {
        "text-color": "#FF7602",
        "text-halo-color": RoadsMajorColor,
        "text-halo-width": 2,
      },
    },

    {
      id: "water",
      type: "symbol",
      source: "features",
      minzoom: 17.75,
      filter: ["==", "kind", "water"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Water",
        "icon-anchor": "center",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "icon-allow-overlap": true,
        "icon-overlap": "cooperative",
        "icon-ignore-placement": true,
        "text-field": "{label}",
        "text-anchor": "top",
        "text-radial-offset": 1,
        "text-justify": "auto",
        "text-font": ["HeroSandwichPro Bold"],
        "text-size": PoiTextSize,
        "icon-size": PoiIconSize,
      },
      paint: {
        "text-color": "#1691AF",
        "text-halo-color": "#FFF",
        "text-halo-width": 2,
      },
    },
    {
      id: "muzeo",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "muzeo"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Museum",
        "icon-anchor": "bottom",
        "text-anchor": "top",
        "text-field": "{label}",
        "text-font": ["HeroSandwichPro Bold"],
        "text-size": PoiTextSize,
        "icon-size": PoiIconSize,
      },
      paint: {
        "text-color": "#703B17",
        "text-halo-color": "#F9F0D3",
        "text-halo-width": 3,
      },
    },
    {
      id: "restaurants",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "restaurants"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Food",
        "icon-anchor": "bottom",
        "text-anchor": "top",
        "text-field": "{label}",
        "text-font": ["HeroSandwichPro Bold"],
        "text-size": PoiTextSize,
        "icon-size": PoiIconSize,
      },
      paint: {
        "text-color": "#703B17",
        "text-halo-color": "#F9F0D3",
        "text-halo-width": 3,
      },
    },
    {
      id: "city-hall",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "city-hall"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Museum",
        "icon-anchor": "bottom",
        "text-anchor": "top",
        "text-field": "{label}",
        "text-font": ["HeroSandwichPro Bold"],
        "text-size": PoiTextSize,
        "icon-size": PoiIconSize,
      },
      paint: {
        "text-color": "#703B17",
        "text-halo-color": "#F9F0D3",
        "text-halo-width": 3,
      },
    },
    {
      id: "text-labels",
      type: "symbol",
      source: "features",
      minzoom: 17,
      filter: ["==", "kind", "text-label"],
      layout: {
        "symbol-placement": "line-center",
        "icon-image": "{icon}",
        "icon-anchor": "center",
        "text-anchor": "center",
        "text-allow-overlap": true,
        "text-ignore-placement": true,
        "icon-allow-overlap": true,
        "icon-overlap": "cooperative",
        "icon-ignore-placement": true,
        "icon-offset": [0, -40],
        "icon-size": PoiIconSize,
        "text-field": "{label}",
        "text-font": ["HeroSandwichPro Bold"],
        "text-size": PoiTextSize,
      },
      paint: {
        "text-color": "#703B17",
        "text-halo-color": "#F9F0D3",
        "text-halo-width": 3,
      },
    },
    {
      id: "parking",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "parking"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Parking",
        "icon-anchor": "center",
        "icon-overlap": "cooperative",
        "icon-size": ["interpolate", ["linear", 1], ["zoom"], 15, 0.65, 20, 1],
        "icon-allow-overlap": true,
        "symbol-sort-key": 80,
      },
    },
    {
      id: "parade-end",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "parade-end"],
      layout: {
        "icon-size": ["interpolate", ["linear", 1], ["zoom"], 13, 0.75, 15, 1],
        "symbol-placement": "point",
        "icon-image": "Parade End",
        "icon-anchor": "bottom-left",
        "icon-allow-overlap": true,
        "icon-offset": [-6, 0],
        "symbol-sort-key": 120,
      },
    },
    {
      id: "parade-callout",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "parade-start"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Parade Start",
        "icon-anchor": "top-right",
        "icon-size": 1,
        "icon-offset": [7, -5],
        "icon-allow-overlap": true,
        "symbol-sort-key": 120,
      },
    },
    {
      id: "car-show-callout",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "car-show"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Car Show",
        "icon-anchor": "bottom",
        "icon-size": 1,
        "icon-offset": [-10, 15],
        "icon-allow-overlap": true,
        "symbol-sort-key": 120,
      },
    },
    {
      id: "festival-callout",
      type: "symbol",
      source: "features",
      filter: ["==", "kind", "festival"],
      layout: {
        "symbol-placement": "point",
        "icon-image": "Festival",
        "icon-anchor": "bottom",
        "icon-size": ["interpolate", ["linear", 1], ["zoom"], 13, 0.75, 15, 1],
        "icon-offset": [-10, 15],
        "icon-allow-overlap": true,
        "symbol-sort-key": 120,
      },
    },
  ],
};
